server {
    listen 80;
    server_name hhscout.su www.hhscout.su;

    # редирект на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # certbot verification
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name hhscout.su www.hhscout.su;

    ssl_certificate /etc/letsencrypt/live/hhscout.su/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hhscout.su/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 30M;
    }

    gzip on;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml;
    gzip_min_length 1024;
    gzip_comp_level 6;
}